-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 14:58:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema beroepsproduct_semester_2_blok_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `beroepsproduct_semester_2_blok_1` ;

-- -----------------------------------------------------
-- Schema beroepsproduct_semester_2_blok_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beroepsproduct_semester_2_blok_1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `beroepsproduct_semester_2_blok_1` ;

-- -----------------------------------------------------
-- Table `beroepsproduct_semester_2_blok_1`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beroepsproduct_semester_2_blok_1`.`team` ;

CREATE TABLE IF NOT EXISTS `beroepsproduct_semester_2_blok_1`.`team` (
  `Team_ID` INT NOT NULL,
  `Team_naam` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Team_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beroepsproduct_semester_2_blok_1`.`persoon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beroepsproduct_semester_2_blok_1`.`persoon` ;

CREATE TABLE IF NOT EXISTS `beroepsproduct_semester_2_blok_1`.`persoon` (
  `Studenten_nummer` INT NOT NULL,
  `Voornaam` VARCHAR(75) NOT NULL,
  `Achternaam` VARCHAR(75) NOT NULL,
  `Geboorte_datum` DATE NOT NULL,
  `Leeftijd` INT NOT NULL,
  `Team_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Studenten_nummer`),
  INDEX `fk_team_ID` (`Team_ID` ASC) VISIBLE,
  CONSTRAINT `fk_team_ID`
    FOREIGN KEY (`Team_ID`)
    REFERENCES `beroepsproduct_semester_2_blok_1`.`team` (`Team_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beroepsproduct_semester_2_blok_1`.`contact_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beroepsproduct_semester_2_blok_1`.`contact_info` ;

CREATE TABLE IF NOT EXISTS `beroepsproduct_semester_2_blok_1`.`contact_info` (
  `Studenten_nummer` INT NOT NULL,
  `Unasat_mail` VARCHAR(100) NULL DEFAULT NULL,
  `Telefoon_nummer` INT NULL DEFAULT NULL,
  `Adres` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`Studenten_nummer`),
  CONSTRAINT `Fk_Contact_ID`
    FOREIGN KEY (`Studenten_nummer`)
    REFERENCES `beroepsproduct_semester_2_blok_1`.`persoon` (`Studenten_nummer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beroepsproduct_semester_2_blok_1`.`ict_vaardigheden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beroepsproduct_semester_2_blok_1`.`ict_vaardigheden` ;

CREATE TABLE IF NOT EXISTS `beroepsproduct_semester_2_blok_1`.`ict_vaardigheden` (
  `Vaardigheid_ID` INT NOT NULL AUTO_INCREMENT,
  `Omschrijving` VARCHAR(100) NOT NULL,
  `Studenten_nummer` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Vaardigheid_ID`),
  INDEX `fk_Studenten_nummer` (`Studenten_nummer` ASC) VISIBLE,
  CONSTRAINT `fk_Studenten_nummer`
    FOREIGN KEY (`Studenten_nummer`)
    REFERENCES `beroepsproduct_semester_2_blok_1`.`persoon` (`Studenten_nummer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
